@ECHO off

SET DAEMON_ROOT=%~dp0

IF "%PROCESSOR_ARCHITECTURE%" == "ARM64" (
    SET DAEMON_APP_ROOT=%DAEMON_ROOT%Windows_ARM64\
) ELSE (
    SET DAEMON_APP_ROOT=%DAEMON_ROOT%Windows\
)

START /B CMD /C "%DAEMON_APP_ROOT%\Tightener.exe" -t n -N daemon -s -l 18888